import 'package:isar/isar.dart';

import '../../../domain/entities/enums.dart';

// Generated by build_runner: `dart run build_runner build`.
part 'library_models.g.dart';

/// Isar persistence model for a [Book].
///
/// Kept separate from the domain `Book` entity so persistence concerns
/// (indexes, the int primary key, enum storage) never leak into the domain.
/// Conversion happens in `data/mappers/book_mappers.dart`.
@collection
class BookModel {
  /// Deterministic primary key = fastHash(uid). Set by the mapper so `put()`
  /// upserts in place.
  Id id = Isar.autoIncrement;

  /// The domain UUID. Indexed for exact lookups and sync keying.
  @Index()
  late String uid;

  @Index(caseSensitive: false, type: IndexType.value)
  late String title;

  @Index(caseSensitive: false, type: IndexType.value)
  late String author;

  @Enumerated(EnumType.name)
  late BookFormat format;

  late String filePath;
  String? coverPath;
  late int fileSizeBytes;
  late int pageCount;

  @Index()
  late DateTime dateImported;

  @Index()
  DateTime? lastOpened;

  late double progressPercent;

  @Index()
  late bool isFavorite;

  @Index()
  late bool isArchived;

  late List<String> collectionIds;

  late bool needsOcr;
  late bool hasSmartContent;

  @Enumerated(EnumType.name)
  late ReadingMode defaultMode;

  String? language;
  String? checksum;
}

/// Isar persistence model for a [Collection].
@collection
class CollectionModel {
  Id id = Isar.autoIncrement;

  @Index()
  late String uid;

  late String name;
  String? description;
  int? colorValue;
  int? iconCodePoint;
  late int sortIndex;
  late DateTime createdAt;

  @Index()
  late DateTime updatedAt;

  @Index()
  late bool isDeleted;
}
